<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>2.1.1.1 Usuario Corecto</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b45aa7c0-fa75-44ba-ac2f-cda58b044d79</testSuiteGuid>
   <testCaseLink>
      <guid>1f94af75-fa16-493d-b3f1-2e7bf29f9677</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/2. Login/2.1 Validacion Boton Login/2.1.1 User/2.1.1.1 Usuario Correcto/Usuario no ingrese al sitio si el pin es incorrecto (C3802)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d09f186-297e-4d9a-accd-1bc680ab1114</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1af9de8-a4bf-4acd-8c11-53fbfdec6431</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36dd5dc2-7a0c-4b5e-98ac-43e4202bedc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dddd112-ead4-4131-b0c4-802518462efc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd3a4236-9ff9-4142-b7b0-21e6027478b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/2. Login/2.1 Validacion Boton Login/2.1.1 User/2.1.1.1 Usuario Correcto/El jugador ingrese al sitio meditante la tecla enter (C3841)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d09f186-297e-4d9a-accd-1bc680ab1114</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1af9de8-a4bf-4acd-8c11-53fbfdec6431</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36dd5dc2-7a0c-4b5e-98ac-43e4202bedc3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
