<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>2.1.2.1 Permiso Correcto</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>8ad52545-f20e-4a50-8054-655b04ac661b</testSuiteGuid>
   <testCaseLink>
      <guid>053e7f4d-fafa-4362-9144-51f4efb1a3d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/2. Login/2.1 Validacion Boton Login/2.1.2 Password/2.1.2.1 Permiso Correcto/Error mediante la tecla enter si la clave es incorrecta C3840</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d09f186-297e-4d9a-accd-1bc680ab1114</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1af9de8-a4bf-4acd-8c11-53fbfdec6431</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36dd5dc2-7a0c-4b5e-98ac-43e4202bedc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e99ce1e5-e28a-4556-a116-4476965bf0e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/2. Login/2.1 Validacion Boton Login/2.1.2 Password/2.1.2.1 Permiso Correcto/Usuario no ingrese al sitio si la clave es incorrecta C3801</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b26d9a6e-2a6e-4ab8-b3d9-1ad351219118</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72c1fa5e-9476-493f-bbff-263050de024f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39af4e11-4e81-44a0-9338-ccd6729c75ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>02667911-4c44-4b6c-8292-d76d98814862</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/2. Login/2.1 Validacion Boton Login/2.1.2 Password/2.1.2.1 Permiso Correcto/Usuario no ingrese si el password no es ingresado C3811</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d09f186-297e-4d9a-accd-1bc680ab1114</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1af9de8-a4bf-4acd-8c11-53fbfdec6431</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId></variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1210dbb3-9aa4-4ae8-8c22-c78ff6169c34</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/2. Login/2.1 Validacion Boton Login/2.1.1 User/2.1.1.1 Usuario Correcto/Usuario no ingrese al sitio si el pin es incorrecto (C3802)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d09f186-297e-4d9a-accd-1bc680ab1114</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1af9de8-a4bf-4acd-8c11-53fbfdec6431</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36dd5dc2-7a0c-4b5e-98ac-43e4202bedc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dddd112-ead4-4131-b0c4-802518462efc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1694d09-d2bd-43a2-94c9-af9c5661a3ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/2. Login/2.1 Validacion Boton Login/2.1.1 User/2.1.1.1 Usuario Correcto/Usuario no ingrese con pin invalido y tecla enter C6415</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2a96fc8-164d-4edd-a6e1-c64ab2e16c64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9a164f2-9ab0-45bd-9051-1398f2dcb8aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a8c7de5-7761-4eca-940a-cc72a6f9860d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ccac1a25-cd36-4218-9f3f-67699385d2bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/2. Login/2.1 Validacion Boton Login/2.1.1 User/2.1.1.1 Usuario Correcto/Usuario no ingrese si el pin no es ingresado (C3810)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f185da1-583f-4543-a535-b03193119533</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18bac46d-7edb-493a-a580-f58c364807ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2a51d30-6a34-436a-8e85-2b03e70d3701</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
