<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>2.1.2.1 Permiso Correcto</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>8ad52545-f20e-4a50-8054-655b04ac661b</testSuiteGuid>
   <testCaseLink>
      <guid>02b2a356-1d9b-460a-b734-d304c20d7899</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/4. Overview/4.3 Product Offer/4.3.2 Sports/4.3.2.1 Account Information/4.3.2.1.1 Pin/El PIN del usuario es el correcto (C3790)</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>53e28952-c5f6-4b02-9b48-7352045eed30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/4. Overview/4.3 Product Offer/4.3.2 Sports/4.3.2.1 Account Information/4.3.2.1.2 Balance/4.3.2.1.2.2 Validacion Balance Vs CM Transactions/Balance Pregame es igual en CM(C3777)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fe154f6-91db-4cde-bc8b-991c573b8973</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bbfd418-7f29-4e1d-918d-3a3e94e58841</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f73099a-d4ac-4ba7-ab90-664b99aa792c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f155484-7ec2-41f9-8313-ce75d383c3e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/4. Overview/4.3 Product Offer/4.3.2 Sports/4.3.2.1 Account Information/4.3.2.1.3 Available/4.3.2.1.3.2 Validacion Available Vs CM Transactions/Disponible pregame es igual a CM (C6387)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccaf515c-b635-4981-b2f7-97443718ad2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c870b682-4569-42b4-beac-81fbbc5e42d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3756b4d2-312d-459e-a0ec-4efb7724ab2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70ba250d-1628-4388-a2ec-2993e7862078</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/4. Overview/4.3 Product Offer/4.3.2 Sports/4.3.2.1 Account Information/4.3.2.1.4 Pending/4.3.2.1.4.2 Validacion Pending Vs CM Transactions/Pendiente hace match con CM(C6391)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d07ae2ce-ce61-477a-b694-ee84ae88ede8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8afea88-af6d-4d2d-b4df-871b01dbf5c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b7c6e39-8984-4df3-a890-43d7e4ba13ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0c9f737-cba4-4bdc-8146-eb4dfdd58825</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/4. Overview/4.3 Product Offer/4.3.2 Sports/4.3.2.1 Account Information/4.3.2.1.5 Free Play/4.3.2.1.5.2 Validacion Free Play Vs CM Transactions/Free Play hace match con CM (C3792)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71505da2-fc0f-441a-a276-327598c3b0ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6de14b99-7d57-4abd-ae46-fb93bb5bb6de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a96642d7-ef0e-4bcf-bbc4-841dd57973e4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
