<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>4.3.2.3.4 Daily Figure</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2b4d2f67-6b25-4cb6-8ecd-c460e3cdff32</testSuiteGuid>
   <testCaseLink>
      <guid>582dce57-12e8-4ae0-a0e8-a0388573fb02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/4. Overview/4.3 Product Offer/4.3.2 Sports/4.3.2.3 My Account/4.3.2.3.4 Daily Figure/Daily figure despliegue las transacciones del lunes de esta semana C6400</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91310968-602f-444d-8838-0bfaee378b99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98ffe2f1-6c3c-401b-b546-2e000ed71bb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d7b018a-304c-4e4b-b911-2597cf3e2de2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>916fb22e-df17-4d03-b062-3afc7f22745a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/4. Overview/4.3 Product Offer/4.3.2 Sports/4.3.2.3 My Account/4.3.2.3.4 Daily Figure/Daily Figure despliegue la transaccion(es) del lunes de la semana pasada C6401</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31be4f8e-dd6c-4304-be19-8c7fa8f8568a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>072db8d3-8ff1-45d6-9059-7f4cf64dba8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fe63696-29b1-4317-b457-4271a7011aa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05031227-0148-432a-a707-9ce281830baa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3e17338-7c4e-4047-85af-855ee4bd3625</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/4. Overview/4.3 Product Offer/4.3.2 Sports/4.3.2.3 My Account/4.3.2.3.4 Daily Figure/Transaccion lunes de esta semana desaparesca con Start from tuesday C6402</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95f39d87-7252-4730-9496-1429e63fc398</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fd0db31-17c2-4941-a791-307dc9589bb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc5edef2-d79b-4fc3-be7c-71a58bcf3223</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
