<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>5.1 Betslip</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ae4e26ba-ed6c-46ae-b3b5-7e6315621d80</testSuiteGuid>
   <testCaseLink>
      <guid>824afa56-360b-4648-944d-69fd6ce5ea60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/5. Betslip/5.1 Bet Type/5.1.1 Straight/Betslip refleje favorito con spread asian 0.25 negative odds con periodo game C6483</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bac87a58-8781-4c42-a115-865446a1d33a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>130ec856-c709-4f38-9b76-0b009009d567</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46adaf0a-c5bd-415b-96d2-144be1833b80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>630fe6fb-a0da-47a0-ad90-51cb9416d539</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33201f78-c25c-47a5-895d-0e81d88d0ef0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2d43ccd-63fe-462b-a2eb-f7e04740a54f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5532d4e9-1308-4cf7-ba9e-72a784a39a85</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fda5e715-6fed-48a5-9404-5322f53ddda1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW PREGAME/5. Betslip/5.1 Bet Type/5.1.1 Straight/Betslip refleje favorito con spread asian 0.25 positive Odds con periodo Game C6484</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4a8ec2c-fe90-4157-a91c-9c6f0675f0cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2782d646-a2d8-407b-93fe-9b38cfb2aaad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bb3e676-08f2-43a3-a34b-41c2adcd6d1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c64706f-ee17-47a6-b048-5247c71a35f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ac13601-86d8-46c9-bf4c-c6ea2bb624d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96c0c783-71b7-4db8-81cd-8dabc19ae0ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d8de03c-a36c-41ba-82af-ec469baa7ba2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
