<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_1NEX</name>
   <tag></tag>
   <elementGuidId>4de0551a-2991-4ea7-8911-644844f20666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/li[@class=&quot;active-result&quot;][count(. | //li[@class = 'active-result' and @data-option-array-index = '1' and (text() = '1NEX' or . = '1NEX')]) = count(//li[@class = 'active-result' and @data-option-array-index = '1' and (text() = '1NEX' or . = '1NEX')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/li[@class=&quot;active-result&quot;]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1NEX</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/li[@class=&quot;active-result&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>/li[@class=&quot;active-result&quot;]
</value>
   </webElementXpaths>
</WebElementEntity>
