<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FadeModal</name>
   <tag></tag>
   <elementGuidId>9d1adeba-8e3b-446f-8569-9dc7463dd2d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.modal-backdrop</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
