<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_groupParlay</name>
   <tag></tag>
   <elementGuidId>a88d447c-e51a-4267-9677-fe28271e5010</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main&quot;)/div[@class=&quot;col-md-12 teaserdetail&quot;]/section[@class=&quot;panel-body&quot;]/table[@class=&quot;table table-bordered&quot;]/tbody[1]/tr[@id=&quot;teasers_detail&quot;]/td[1]/div[@class=&quot;btn-group btn-group-justified&quot;]/table[@class=&quot;table table-bordered header-fixed1&quot;]/tbody[@id=&quot;teasearsDetail&quot;]/tr[1]/td[1]/div[1]/div[@class=&quot;input-group&quot;]/span[@class=&quot;input-group-addon&quot;]/input[@class=&quot;cateMix bloquear&quot;][count(. | //input[@name = 'groupParlay' and @value = 'FB 2-10T -10PT TL' and @type = 'checkbox']) = count(//input[@name = 'groupParlay' and @value = 'FB 2-10T -10PT TL' and @type = 'checkbox'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='groupParlay'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cateMix bloquear</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupParlay</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FB 2-10T -10PT TL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SaveTeaserSession('FB 2-10T -10PT TL','FOOTBALL: College (T) -10 PTS,  (S) -10 PTS, NFL (T) -10 PTS,  (S) -10 PTS, Pre-Season (T) -10 PTS,  (S) -10 PTS;TIES LOSE')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;col-md-12 teaserdetail&quot;]/section[@class=&quot;panel-body&quot;]/table[@class=&quot;table table-bordered&quot;]/tbody[1]/tr[@id=&quot;teasers_detail&quot;]/td[1]/div[@class=&quot;btn-group btn-group-justified&quot;]/table[@class=&quot;table table-bordered header-fixed1&quot;]/tbody[@id=&quot;teasearsDetail&quot;]/tr[1]/td[1]/div[1]/div[@class=&quot;input-group&quot;]/span[@class=&quot;input-group-addon&quot;]/input[@class=&quot;cateMix bloquear&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>(//input[@name='groupParlay'])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//tbody[@id='teasearsDetail']/tr/td/div/div/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TeaserName'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FOOTBALL: College (S) -10 PTS, NFL (S) -10 PTS, Pre-Season (S) -10 PTS;TIES LOSE'])[1]/preceding::input[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FOOTBALL: Arena (S) -6 PTS, Canadian (S) -6 PTS, College (S) -6 PTS;TIES LOSE'])[1]/preceding::input[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//td/div/div/span/input</value>
   </webElementXpaths>
</WebElementEntity>
